### PR TITLE
List of agency names that own City property

### PR DESCRIPTION
**Pull request by juansvas**
- List of 55 names that appear on County Assessor records of LA City agencies who own properties. 
- Noted which files are connected to this list and included relevant links.

### CODE REVIEW

**Comment by cityhubla** [comment]
Looks good, @machikoyasuda, any thoughts? We are listing all related agencies that are part of LA City, a list posted on the read.me would show our efforts and methods in identifying properties.

**Comment by cityhubla** [comment]
I'm also wondering if this is the best way to display a list as long as this or should we make a table?

**Comment by machikoyasuda** [comment]
We could number them and put them in a table:

This website can generate the Markdown code from pasting a CSV: https://donatstudios.com/CsvToMarkdownTable

Maybe we should also normalize the data.. like some say "LA" and some say "L A"

**Comment by michaelkirk** [comment]
Plain text in a separate file would be good. Then it could be used as input to a cleaning script. I'm happy to implement that if y'all think it's a good idea.

**Comment by michaelkirk** [comment]
@juansvas can we close this PR since #21 contains all the city agencies. And maybe put the explanation in the datacatalog (#22 )?

**Comment by juansvas** [comment]
Good call @michaelkirk  - I added the explanation and a table of the 55 agencies/name variations to https://github.com/maptimeLA/project-sandbox/pull/22. Will close #17 now

**Pull request closed without merging**
